### ISSUE TITLE
Android Phone Issues

### ISSUE THREAD

**Issue by menasheh** [cykod/Quintus#153]
I can't get some parts of the Quintus engine to run in the android browser Jasmine gets 9 graphics errors with the following reason:

The canvas has been tainted by cross origin data 

Chrome gets an additional timeout failure issue:

Timed out after 600 milliseconds waiting for callback should be called

**Comment by cykod** [comment]
Are you loading resources cross-domain? I don't believe this is a Quintus related problem - if you believe it is, please reopen, provide a stack trace and a link to bug in action.

**Comment by menasheh** [comment]
I was using a file:/// url

**Comment by cykod** [comment]
I have no idea what the "callback failure in Chrome" would be - if you can provide a stack trace on any of this, it would help trying to diagnose the issue.
