### ISSUE TITLE
Gap with TMX map and spacing tileset

### ISSUE THREAD

**Issue by Sparksx** [cykod/Quintus#165]
Hello

I use an TMX map with 1px spacing between tiles.
Tiles on first line are correctly rendered. But other line have tiles gap.
line 2 : 1 tile gap
Line 3 : 2 tiles gap
etc

I use this tileset (16 x 16 with 1px spacing)
![roguelikesheet_transparent](https://cloud.githubusercontent.com/assets/3260152/8110555/42f58246-105d-11e5-9581-265b28759e5e.png)
My tmx file : 
http://paf.im/WTrxX

I've a bad config or it's a bug ?

**Comment by benpaddlejones** [comment]
This is an issue with Tiled not Quintus, suggest you ask question such as this direct to Tiled or the Quintus Google+ group.

**Comment by Sparksx** [comment]
I go to ask this !
But did you recommend me an other software like tiled ?

Thanks

**Comment by Sparksx** [comment]
Hi,

I have found the solution : my tilset is composed of 16px tiles with 1px spacing.
the last line tiles haven't the 1px spacing on right, so Quintus don't find him.

I've just add 1px spacing to correct this.

**Comment by Sparksx** [comment]
Someone who work on tiled map editor say me tileset didn't need spacing at right of last line tile. So you have a bug with rendering when tilset have spacing and last line tile don't have.

**Comment by benpaddlejones** [comment]
Is the issue in Tiled or when the tmx is loaded into a browser by quintus?

**Comment by Sparksx** [comment]
It's in tiled but I've do a pull request to correct it
