### ISSUE TITLE
Solve "scale-to-fit" issues once and for all

### ISSUE THREAD

**Issue by cykod** [cykod/Quintus#53]
Simplify the setup method to handle the 3 scaling variations:
1. exact size
2. exact pixel size, scale CSS up to maximize while keeping aspect ratio and make sure input handles this
3. maximize, scaling up the pixel size

Also see if retina (2x resolution) can be handled and low-power (1/2x resolution) can be handled cleanly.

**Comment by JaredSartin** [comment]
Why was this closed? This is only using scale 1: see line note on d428cd715fb96ce2db4408ca6ed2b087ee0e485e
